name 'resources'
maintainer 'Austin Heiman'
maintainer_email 'atheimanksu@gmail.com'
license 'all_rights'
description 'Installs/Configures resources'
long_description 'Installs/Configures resources'
version '0.1.0'

issues_url 'https://github.com/atheiman/resources-cookbook/issues'
source_url 'https://github.com/atheiman/resources-cookbook'
